# Generate code for all the packages with dynamic features
watch:
	@echo "==> 👀 Watching for changes in packages with dynamic features"
	@flutter pub run build_runner watch --delete-conflicting-outputs --verbose
